#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
        sh "npm -version"
    }

    stage('backend tests') {
        sh "./mvnw -ntp verify"
    }

    stage('packaging') {
        sh "./mvnw package -DskipTests"
        archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
    }
}
